SELECT R.NAME AS REGIONNAME,
	S.NAME AS REPSNAME,
	AC.NAME AS ACCOUNTNAME
FROM ACCOUNTS AC
JOIN SALES_REPS S ON AC.SALES_REP_ID = S.ID
JOIN REGION R ON S.REGION_ID = R.ID
WHERE R.NAME IN ('Midwest')
ORDER BY AC.NAME
LIMIT 10